export const ONE_MINUTE_IN_SECONDS = 60;
export const ONE_HOUR_IN_MINUTES = 60;
export const ONE_DAY_IN_HOURS = 24;
export const ONE_YEAR_IN_DAYS = 365;

export const ONE_YEAR_IN_SECONDS =
  ONE_YEAR_IN_DAYS * ONE_DAY_IN_HOURS * ONE_HOUR_IN_MINUTES * ONE_MINUTE_IN_SECONDS;
